INSERT INTO exam_questions (subject, grade, question_type, question_text, options, answer, explanation, difficulty, topic)
VALUES
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'When the teacher says ''Open your book to page 25'', what should you do?', '["เปิดหนังสือไปที่หน้า 25","ปิดหนังสือหน้าที่ 25","เขียนหนังสือ 25 หน้า","อ่านหนังสือ 25 เล่ม"]'::jsonb, '0'::jsonb, '''Open your book'' แปลว่า เปิดหนังสือของคุณ และ ''page 25'' คือ หน้า 25', 'easy', '[ต 1.1 ป.4/1] คำสั่งในห้องเรียน (Classroom Commands)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Which animal has a very long neck and eats leaves from tall trees?', '["Giraffe","Elephant","Monkey","Tiger"]'::jsonb, '0'::jsonb, 'Giraffe (ยีราฟ) เป็นสัตว์ที่มีคอยาวมาก และกินใบไม้จากต้นไม้สูง', 'easy', '[ต 1.1 ป.4/2] คำศัพท์เกี่ยวกับสัตว์ (Animals)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'A sign says ''No Smoking''. What does it mean?', '["ห้ามสูบบุหรี่","ห้ามส่งเสียงดัง","ห้ามทิ้งขยะ","ห้ามถ่ายรูป"]'::jsonb, '0'::jsonb, '''No Smoking'' แปลว่า ห้ามสูบบุหรี่', 'easy', '[ต 1.1 ป.4/3] ป้ายสัญลักษณ์ (Signs & Symbols)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'What should you say to greet your teacher at 8:00 in the morning?', '["Good morning","Good afternoon","Good evening","Good night"]'::jsonb, '0'::jsonb, 'เวลา 8:00 น. ในตอนเช้า ต้องใช้คำทักทายว่า ''Good morning''', 'easy', '[ต 1.2 ป.4/1] การทักทายตามช่วงเวลา (Greetings)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'When someone gives you a birthday gift, what is the best response?', '["Thank you very much!","I am sorry.","You are welcome.","Goodbye."]'::jsonb, '0'::jsonb, 'เมื่อมีคนให้ของขวัญหรือช่วยเหลือ เราควรกล่าวขอบคุณว่า ''Thank you very much!''', 'easy', '[ต 1.2 ป.4/1] การขอบคุณ (Thanking)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Your mother''s father is your _______.', '["grandfather","grandmother","uncle","brother"]'::jsonb, '0'::jsonb, 'คุณพ่อของคุณแม่ คือ คุณตา ซึ่งในภาษาอังกฤษใช้คำว่า ''grandfather''', 'easy', '[ต 1.2 ป.4/4] คำศัพท์หมวดครอบครัว (Family Members)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'In which subject do you study about numbers, addition, and shapes?', '["Mathematics","English","Art","Music"]'::jsonb, '0'::jsonb, 'วิชาที่เรียนเกี่ยวกับตัวเลข การบวกเลข และรูปทรงเรขาคณิต คือ ''Mathematics'' (คณิตศาสตร์)', 'easy', '[ต 1.3 ป.4/1] คำศัพท์วิชาเรียน (School Subjects)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'What color do you get when you mix yellow and blue?', '["Green","Purple","Orange","Black"]'::jsonb, '0'::jsonb, 'เมื่อผสมสีเหลือง (Yellow) กับสีน้ำเงิน (Blue) จะได้สีเขียว (Green)', 'easy', '[ต 1.3 ป.4/1] คำศัพท์บอกสี (Colors)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Christmas Day is celebrated on which date every year?', '["December 25th","December 31st","January 1st","October 31st"]'::jsonb, '0'::jsonb, 'วันคริสต์มาสตรงกับวันที่ 25 ธันวาคม (December 25th) ของทุกปี', 'easy', '[ต 2.1 ป.4/1] วันคริสต์มาส (Christmas Day)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'The cat is sleeping _______ the table. (ใต้โต๊ะ)', '["under","on","in","above"]'::jsonb, '0'::jsonb, '''under'' แปลว่า ใต้ หรือ ข้างใต้ (under the table = ใต้โต๊ะ)', 'easy', '[ต 1.2 ป.4/2] คำบุพบทบอกตำแหน่ง (Prepositions)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'What time is it if the short hand points to 3 and the long hand points to 12?', '["It is three o''clock.","It is twelve o''clock.","It is half past three.","It is three thirty."]'::jsonb, '0'::jsonb, 'เข็มสั้นชี้เลข 3 เข็มยาวชี้เลข 12 คือเวลา 3 นาฬิกาตรง (''It is three o''clock.'')', 'easy', '[ต 1.2 ป.4/3] การบอกเวลา (Telling Time)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Look at the sun! It is very bright and hot today. The weather is _______.', '["sunny","rainy","snowy","windy"]'::jsonb, '0'::jsonb, 'แดดจัดและอากาศร้อน บ่งบอกถึงสภาพอากาศที่มีแดดออกจ้า เรียกว่า ''sunny''', 'easy', '[ต 1.3 ป.4/1] คำศัพท์สภาพอากาศ (Weather)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'A person who flies an airplane is a _______.', '["pilot","doctor","chef","police officer"]'::jsonb, '0'::jsonb, 'ผู้ที่ขับเครื่องบิน เรียกว่า ''pilot'' (นักบิน)', 'easy', '[ต 1.1 ป.4/2] คำศัพท์เกี่ยวกับอาชีพ (Occupations)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Jenny is a smart student. _______ always reads books.', '["She","He","It","They"]'::jsonb, '0'::jsonb, 'Jenny เป็นผู้หญิงเอกพจน์ คำสรรพนามที่ใช้แทนคือ ''She''', 'easy', '[ต 1.2 ป.4/2] คำสรรพนาม (Pronouns)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Which month is the first month of the calendar year?', '["January","February","December","April"]'::jsonb, '0'::jsonb, 'เดือนมกราคม (January) เป็นเดือนแรกของปีตามปฏิทินสากล', 'easy', '[ต 1.1 ป.4/2] คำศัพท์เกี่ยวกับเดือน (Months of the Year)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Tom _______ to school by bicycle every morning.', '["goes","go","going","went"]'::jsonb, '0'::jsonb, 'Tom เป็นประธานเอกพจน์บุรุษที่ 3 ในประโยค Present Simple Tense กริยาต้องเติม -es (go -> goes)', 'medium', '[ต 1.2 ป.4/1] โครงสร้าง Present Simple Tense'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Look! The children _______ football in the playground right now.', '["are playing","is playing","plays","played"]'::jsonb, '0'::jsonb, '''The children'' เป็นพหูพจน์ และมีคำว่า ''right now'' กริยาต้องเป็น are + V.ing (''are playing'')', 'medium', '[ต 1.2 ป.4/1] โครงสร้าง Present Continuous Tense'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'A bird can fly, but a penguin _______ fly.', '["cannot","can","must","should"]'::jsonb, '0'::jsonb, 'นกเพนกวินเป็นนกที่ว่ายน้ำได้แต่ไม่สามารถบินได้ จึงใช้คำว่า ''cannot'' หรือ ''can''t''', 'medium', '[ต 1.2 ป.4/2] การใช้ Can / Can''t'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'My brother _______ a new computer in his bedroom.', '["has got","have got","having","is having"]'::jsonb, '0'::jsonb, 'My brother เป็นประธานเอกพจน์ จึงใช้ ''has got'' (ถ้าพหูพจน์ใช้ have got)', 'medium', '[ต 1.2 ป.4/2] การใช้ Have / Has got'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'A: ''_______ do you live?''
B: ''I live in Bangkok, Thailand.''', '["Where","When","Who","What"]'::jsonb, '0'::jsonb, 'คำตอบเป็นสถานที่ (Bangkok) คำถามจึงต้องขึ้นต้นด้วย ''Where'' (ที่ไหน)', 'medium', '[ต 1.2 ป.4/3] คำถาม Wh-Questions (Where)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'A: ''_______ do you get up in the morning?''
B: ''At six o''clock.''', '["What time","How many","Where","Why"]'::jsonb, '0'::jsonb, 'คำตอบเป็นเวลา (At six o''clock) จึงต้องถามด้วย ''What time'' (เวลาเท่าใด)', 'medium', '[ต 1.2 ป.4/3] คำถาม Wh-Questions (What time)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'A: ''_______ is this blue pencil case?''
B: ''It is 45 baht.''', '["How much","How many","How old","How tall"]'::jsonb, '0'::jsonb, 'การถามราคาสินค้าใช้โครงสร้าง ''How much is / are ...?''', 'medium', '[ต 1.2 ป.4/4] การถามราคา (How much)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'A: ''_______ apples are there in the basket?''
B: ''There are five apples.''', '["How many","How much","How long","How often"]'::jsonb, '0'::jsonb, 'ถามจำนวนนามนับได้พหูพจน์ (apples) ใช้โครงสร้าง ''How many''', 'medium', '[ต 1.2 ป.4/4] การถามจำนวน (How many)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'What is the plural form of the word ''child''?', '["children","childs","childes","childrens"]'::jsonb, '0'::jsonb, 'คำว่า ''child'' (เด็ก 1 คน) เมื่อเป็นพหูพจน์ (เด็กหลายคน) จะเปลี่ยนรูปเป็น ''children''', 'medium', '[ต 1.3 ป.4/1] พหูพจน์เปลี่ยนรูป (Irregular Plural Nouns)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'You should brush your _______ twice a day.', '["teeth","tooths","tooth","teethes"]'::jsonb, '0'::jsonb, 'ฟันหลายซี่เปลี่ยนรูปจาก ''tooth'' เป็น ''teeth''', 'medium', '[ต 1.3 ป.4/1] พหูพจน์เปลี่ยนสระ (Irregular Plural Nouns)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'The hospital is _______ the bank and the post office.', '["between","in","under","on"]'::jsonb, '0'::jsonb, 'เมื่ออยู่ท่ามกลางสิ่งของสองแห่ง (the bank and the post office) ใช้คำบุพบท ''between'' (ระหว่าง)', 'medium', '[ต 1.2 ป.4/2] คำบุพบทบอกตำแหน่ง (between)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', '_______ some milk in the glass.', '["There is","There are","There were","There have"]'::jsonb, '0'::jsonb, '''milk'' เป็นคำนามนับไม่ได้ จัดเป็นรูปเอกพจน์ จึงต้องใช้ ''There is''', 'medium', '[ต 1.2 ป.4/2] การใช้ There is / There are'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'If you want to go to the toilet during class, what is the most polite question to ask your teacher?', '["May I go to the toilet, please?","I go toilet now.","Can I sleep here?","Give me toilet key."]'::jsonb, '0'::jsonb, 'การขออนุญาตคุณครูอย่างสุภาพ ใช้โครงสร้าง ''May I ..., please?''', 'medium', '[ต 1.2 ป.4/1] การขออนุญาตอย่างสุภาพ (May I...)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'What phrase do children say when they knock on doors for candy on Halloween?', '["Trick or Treat!","Merry Christmas!","Happy Birthday!","Happy New Year!"]'::jsonb, '0'::jsonb, 'ในวันฮาโลวีน เด็กๆ แต่งชุดแฟนซีไปเคาะประตูตามบ้านและพูดว่า ''Trick or Treat!'' เพื่อขอขนมหวาน', 'medium', '[ต 2.1 ป.4/1] เทศกาลฮาโลวีน (Halloween)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Read the sentence: ''Ladda likes bananas and apples, but she doesn''t like durian.'' What fruit does Ladda dislike?', '["Durian","Banana","Apple","Mango"]'::jsonb, '0'::jsonb, 'ข้อความระบุว่า ''she doesn''t like durian'' แสดงว่าลัดดาไม่ชอบทุเรียน', 'medium', '[ต 1.1 ป.4/4] การอ่านบทความสั้น (Reading Comprehension)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'What is the opposite word of ''difficult''?', '["easy","hard","heavy","slow"]'::jsonb, '0'::jsonb, 'difficult แปลว่า ยาก คำตรงข้ามคือ ''easy'' (ง่าย)', 'medium', '[ต 1.2 ป.4/4] คำคุณศัพท์ตรงข้าม (Opposites)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'They _______ like spicy food.', '["don''t","doesn''t","aren''t","isn''t"]'::jsonb, '0'::jsonb, 'ประธาน ''They'' เป็นพหูพจน์ ในประโยคปฏิเสธของกริยาทั่วไป (like) ต้องใช้กริยาช่วย ''don''t'' (do not)', 'medium', '[ต 1.2 ป.4/1] ประโยคปฏิเสธ Present Simple'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'An elephant is _______ than a dog.', '["bigger","big","biggest","more big"]'::jsonb, '0'::jsonb, 'การเปรียบเทียบขั้นกว่าของคำว่า big มี 1 พยางค์ สระเสียงสั้น ให้เบิ้ลตัวสะกดแล้วเติม -er เป็น ''bigger than''', 'medium', '[ต 1.2 ป.4/1] การเปรียบเทียบขั้นกว่า (Comparative Adjectives)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'What do you do right after you wake up and get out of bed?', '["I brush my teeth and wash my face.","I go to bed.","I have dinner.","I watch evening news."]'::jsonb, '0'::jsonb, 'หลังจากตื่นนอนตอนเช้า กิจวัตรแรกคือแปรงฟันและล้างหน้า (''brush my teeth and wash my face'')', 'medium', '[ต 1.3 ป.4/1] กิจวัตรประจำวัน (Daily Routines)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'You see a sign with an image of a red circle and a line across a horn. What does it mean?', '["Do not blow your car horn (No honking)","Speed limit 50","Stop here","Turn left only"]'::jsonb, '0'::jsonb, 'รูปแตรมีเส้นขีดฆ่า หมายถึง ห้ามบีบแตร (มักติดบริเวณโรงพยาบาลหรือโรงเรียน)', 'medium', '[ต 1.1 ป.4/3] ป้ายจราจรและสถานที่ (Signs)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Dan never eats vegetables. How often does he eat vegetables?', '["0% (Not even once)","100% (Every day)","50% (Sometimes)","80% (Usually)"]'::jsonb, '0'::jsonb, 'คำว่า ''never'' หมายถึง ไม่เคยเลย (0%)', 'medium', '[ต 1.2 ป.4/2] คำบอกความถี่ (Adverbs of Frequency)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Which of the following is considered healthy food?', '["Salad and fresh milk","Potato chips and soda","Candy and cola","Donut and fried chicken skin"]'::jsonb, '0'::jsonb, 'สลัดผักและนมสดจืด (Salad and fresh milk) เป็นอาหารที่มีประโยชน์ต่อสุขภาพ', 'medium', '[ต 1.3 ป.4/1] อาหารและเครื่องดื่ม (Food and Drinks)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'A: ''How do you feel today?''
B: ''I won the English speech contest, so I am very _______.''', '["happy and proud","sad and crying","tired and sleepy","angry"]'::jsonb, '0'::jsonb, 'เมื่อชนะการแข่งขันย่อมรู้สึกมีความสุขและภาคภูมิใจ (''happy and proud'')', 'medium', '[ต 1.2 ป.4/3] คำถามเกี่ยวกับความรู้สึก (Feelings)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Which sentence has the correct English word order?', '["She wears a beautiful red dress.","She wears a dress red beautiful.","She wears a red dress beautiful.","She wears dress a beautiful red."]'::jsonb, '0'::jsonb, 'ในภาษาอังกฤษ คำคุณศัพท์ (Adjective) จะวางหน้าคำนามเสมอ: beautiful red dress (ชุดกระโปรงสีแดงที่สวยงาม)', 'medium', '[ต 2.2 ป.4/1] การเรียงคำคุณศัพท์หน้าคำนาม'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Which word rhymes with ''cake''?', '["lake","cat","car","book"]'::jsonb, '0'::jsonb, '''lake'' ออกเสียงสระ /eɪk/ คล้องจองกับ ''cake''', 'medium', '[ต 1.1 ป.4/2] การสะกดคำและการออกเสียง (Phonics)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'My father usually _______ coffee, but today he _______ tea.', '["drinks, is drinking","is drinking, drinks","drink, is drinking","drinks, drink"]'::jsonb, '0'::jsonb, 'ส่วนแรกมี ''usually'' แสดงกิจวัตรเป็น Present Simple (drinks) ส่วนหลังมี ''today'' แสดงสิ่งที่ทำเฉพาะวันนี้เป็น Present Continuous (is drinking)', 'hard', '[ต 1.2 ป.4/1] การแยกแยะ Present Simple vs Present Continuous'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Read the story:
''Ben has a dog named Max. Max is brown with white paws. Every afternoon after school, Ben throws a red rubber ball, and Max runs to bring it back.''
What is Max''s favorite activity in the afternoon?', '["Playing fetch with a red rubber ball","Sleeping on the sofa all day","Eating chocolate and cookies","Swimming in the deep river"]'::jsonb, '0'::jsonb, 'จากเนื้อเรื่อง เบนปาลูกบอลยางสีแดง และแม็กซ์วิ่งไปคาบกลับมา เรียกว่าการเล่นคาบของ (Playing fetch)', 'hard', '[ต 1.1 ป.4/4] การอ่านจับใจความและสรุปความ (Reading Passage)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'There aren''t _______ students in the library, and there isn''t _______ water left in the cooler.', '["many, much","much, many","many, many","much, much"]'::jsonb, '0'::jsonb, '''students'' เป็นนามนับได้พหูพจน์จึงใช้ ''many'' ส่วน ''water'' เป็นนามนับไม่ได้จึงใช้ ''much''', 'hard', '[ต 1.2 ป.4/4] การใช้ Much vs Many กับคำนามนับได้/นับไม่ได้'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Mount Everest is _______ mountain in the world.', '["the highest","higher","the most high","highest"]'::jsonb, '0'::jsonb, 'การเปรียบเทียบขั้นสูงสุด ต้องมี ''the'' นำหน้า และเติม -est: ''the highest mountain'' (ยอดเขาที่สูงที่สุดในโลก)', 'hard', '[ต 1.2 ป.4/1] การเปรียบเทียบขั้นสูงสุด (Superlative Adjectives)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Our school sports day will take place _______ Friday morning, _______ 8:30 a.m.', '["on, at","in, on","at, in","on, in"]'::jsonb, '0'::jsonb, 'ใช้วันในสัปดาห์ (Friday) ใช้บุพบท ''on'' ส่วนเวลาเฉพาะเจาะจง (8:30 a.m.) ใช้บุพบท ''at''', 'hard', '[ต 1.2 ป.4/2] คำบุพบทเกี่ยวกับเวลา (Prepositions of Time: in, on, at)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Peter: ''I lost my English homework notebook.''
What is the most sympathetic response?', '["I am sorry to hear that. Can I help you look for it?","That is fantastic news!","You are very welcome.","Don''t talk to me."]'::jsonb, '0'::jsonb, 'เมื่อเพื่อนทำของหาย ควรแสดงความเห็นใจและเสนอความช่วยเหลือว่า ''I am sorry to hear that. Can I help you look for it?''', 'hard', '[ต 1.2 ป.4/3] การตอบคำถามในสถานการณ์สังคม (Polite Social Response)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Neither of the two pens _______ on my desk.', '["is","are","were","have"]'::jsonb, '0'::jsonb, '''Neither of ...'' ถือเป็นประธานเอกพจน์ทางไวยากรณ์ กริยาจึงต้องใช้ ''is''', 'hard', '[ต 1.3 ป.4/1] การเลือกใช้คำกริยาให้สอดคล้องกับประธาน (Subject-Verb Agreement)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Which traditional food is commonly served as the main course on Thanksgiving dinner in America?', '["Roast turkey and pumpkin pie","Spaghetti and pizza","Sushi and sashimi","Fried rice and spring rolls"]'::jsonb, '0'::jsonb, 'อาหารจานหลักดั้งเดิมในวันขอบคุณพระเจ้า (Thanksgiving) ของสหรัฐอเมริกา คือ ไก่งวงอบ (Roast turkey) และพายฟักทอง (Pumpkin pie)', 'hard', '[ต 2.1 ป.4/2] วัฒนธรรมและเทศกาลวันขอบคุณพระเจ้า (Thanksgiving)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'Look at the timetable:
- 09:00 - 10:00: Math
- 10:00 - 10:15: Break
- 10:15 - 11:15: English
- 11:15 - 12:15: Science
What class do the students attend right after the morning break?', '["English","Math","Science","Lunch"]'::jsonb, '0'::jsonb, 'ช่วงพักเบรกคือ 10:00 - 10:15 วิชาที่เรียนต่อทันทีหลังพักเบรก (10:15 - 11:15) คือ ''English''', 'hard', '[ต 1.1 ป.4/4] การวิเคราะห์ตารางเวลาเรียน (Timetable Analysis)'),
  ('ภาษาอังกฤษ', 'ป.4', 'mcq', 'This is not my schoolbag. _______ is dark blue, but this one is black.', '["Mine","My","Me","I"]'::jsonb, '0'::jsonb, '''Mine'' เป็น Possessive Pronoun ที่ทำหน้าที่เป็นประธานแทนคำว่า ''My schoolbag'' โดยไม่ต้องมีคำนามตามหลัง', 'hard', '[ต 1.2 ป.4/1] คำสรรพนามแสดงความเป็นเจ้าของ (Possessive Pronouns)');
