-- 397_pixel_forest_rpg_vertical_slice.sql
-- Persistent RPG profile/economy/telemetry for pixel-forest-explorer v3.0.0.
-- Student identity follows the existing game boundary: a valid active student_code.

CREATE TABLE IF NOT EXISTS public.pixel_forest_rpg_profiles (
  student_id       uuid PRIMARY KEY REFERENCES public.students(id) ON DELETE CASCADE,
  hero_class       text CHECK (hero_class IS NULL OR hero_class IN ('swordsman', 'ranger', 'mage')),
  hero_level       int NOT NULL DEFAULT 1 CHECK (hero_level BETWEEN 1 AND 50),
  hero_xp          int NOT NULL DEFAULT 0 CHECK (hero_xp BETWEEN 0 AND 10000000),
  gold             int NOT NULL DEFAULT 150 CHECK (gold BETWEEN 0 AND 10000000),
  gems             int NOT NULL DEFAULT 0 CHECK (gems BETWEEN 0 AND 1000000),
  current_chapter  int NOT NULL DEFAULT 1 CHECK (current_chapter BETWEEN 1 AND 4),
  current_zone     text NOT NULL DEFAULT 'village' CHECK (current_zone IN ('village', 'mosswood', 'swamp', 'ruins')),
  save_state       jsonb NOT NULL DEFAULT jsonb_build_object(
    'schema_version', 1,
    'hero_class', NULL,
    'hero_level', 1,
    'hero_xp', 0,
    'skill_points', 0,
    'gold', 150,
    'gems', 0,
    'chapter', 1,
    'zone', 'village',
    'unlocked_zones', jsonb_build_array('village'),
    'quest', jsonb_build_object('chapter', 1, 'kills', 0, 'boss_defeated', false),
    'equipment', jsonb_build_object('weapon', jsonb_build_object('code', 'training-weapon', 'enhance', 0, 'rune', NULL)),
    'inventory', jsonb_build_object('moss', 0, 'wood', 0, 'slime_core', 0, 'swamp_ore', 0, 'ancient_shard', 0),
    'runes', '[]'::jsonb,
    'bosses', '{}'::jsonb,
    'play_seconds', 0
  ),
  state_version    int NOT NULL DEFAULT 1 CHECK (state_version > 0),
  last_save_key    text,
  last_played_at   timestamptz NOT NULL DEFAULT now(),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pixel_forest_economy_ledger (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id       uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  currency         text NOT NULL CHECK (currency IN ('gold', 'gems')),
  amount           int NOT NULL CHECK (amount <> 0),
  balance_after    int NOT NULL CHECK (balance_after >= 0),
  reason           text NOT NULL CHECK (reason IN ('loot', 'quest', 'boss', 'craft', 'enhance', 'rune', 'migration', 'save_sync')),
  idempotency_key  text NOT NULL,
  metadata         jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (student_id, idempotency_key, currency)
);

CREATE INDEX IF NOT EXISTS idx_pixel_forest_ledger_student_time
  ON public.pixel_forest_economy_ledger (student_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.pixel_forest_balance_events (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id    uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  event_type    text NOT NULL CHECK (event_type IN (
    'session_start', 'session_end', 'class_selected', 'zone_enter', 'monster_kill',
    'player_death', 'boss_start', 'boss_clear', 'chapter_complete', 'item_craft',
    'weapon_enhance', 'rune_equip', 'damage_dealt', 'damage_taken'
  )),
  hero_class    text CHECK (hero_class IS NULL OR hero_class IN ('swordsman', 'ranger', 'mage')),
  hero_level    int CHECK (hero_level IS NULL OR hero_level BETWEEN 1 AND 50),
  chapter       int CHECK (chapter IS NULL OR chapter BETWEEN 1 AND 4),
  zone          text CHECK (zone IS NULL OR zone IN ('village', 'mosswood', 'swamp', 'ruins')),
  value         numeric,
  metadata      jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pixel_forest_events_type_time
  ON public.pixel_forest_balance_events (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pixel_forest_events_class_zone
  ON public.pixel_forest_balance_events (hero_class, zone, created_at DESC);

ALTER TABLE public.pixel_forest_rpg_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pixel_forest_economy_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pixel_forest_balance_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pixel_forest_profiles_admin_all ON public.pixel_forest_rpg_profiles;
CREATE POLICY pixel_forest_profiles_admin_all ON public.pixel_forest_rpg_profiles
  FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

DROP POLICY IF EXISTS pixel_forest_ledger_admin_all ON public.pixel_forest_economy_ledger;
CREATE POLICY pixel_forest_ledger_admin_all ON public.pixel_forest_economy_ledger
  FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

DROP POLICY IF EXISTS pixel_forest_events_admin_all ON public.pixel_forest_balance_events;
CREATE POLICY pixel_forest_events_admin_all ON public.pixel_forest_balance_events
  FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

-- 2026 Data API defaults may be opt-in. Direct tables remain admin-only via RLS;
-- student game clients use the validated RPCs below.
REVOKE ALL ON public.pixel_forest_rpg_profiles FROM anon;
REVOKE ALL ON public.pixel_forest_economy_ledger FROM anon;
REVOKE ALL ON public.pixel_forest_balance_events FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pixel_forest_rpg_profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pixel_forest_economy_ledger TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pixel_forest_balance_events TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.pixel_forest_balance_events_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION public.get_pixel_forest_rpg_state(p_student_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
  v_student_id uuid;
  v_profile public.pixel_forest_rpg_profiles%ROWTYPE;
BEGIN
  SELECT s.id INTO v_student_id
  FROM public.students s
  WHERE s.student_code = btrim(p_student_code)
    AND s.is_active IS NOT FALSE
  LIMIT 1;

  IF v_student_id IS NULL THEN
    RAISE EXCEPTION 'RPG_STUDENT_NOT_FOUND';
  END IF;

  INSERT INTO public.pixel_forest_rpg_profiles (student_id)
  VALUES (v_student_id)
  ON CONFLICT (student_id) DO NOTHING;

  SELECT * INTO v_profile
  FROM public.pixel_forest_rpg_profiles
  WHERE student_id = v_student_id;

  RETURN jsonb_build_object(
    'state_version', v_profile.state_version,
    'save_state', v_profile.save_state,
    'saved_at', v_profile.updated_at
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.save_pixel_forest_rpg_state(
  p_student_code text,
  p_expected_version int,
  p_idempotency_key text,
  p_state jsonb,
  p_events jsonb DEFAULT '[]'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
  v_student_id uuid;
  v_profile public.pixel_forest_rpg_profiles%ROWTYPE;
  v_class text;
  v_level int;
  v_xp int;
  v_gold int;
  v_gems int;
  v_chapter int;
  v_zone text;
  v_gold_delta int;
  v_gem_delta int;
  v_event jsonb;
  v_new_version int;
BEGIN
  IF p_idempotency_key IS NULL OR char_length(p_idempotency_key) NOT BETWEEN 8 AND 80
     OR p_idempotency_key !~ '^[a-zA-Z0-9:_-]+$' THEN
    RAISE EXCEPTION 'RPG_INVALID_SAVE_KEY';
  END IF;
  IF p_state IS NULL OR jsonb_typeof(p_state) <> 'object'
     OR octet_length(p_state::text) > 100000 THEN
    RAISE EXCEPTION 'RPG_INVALID_STATE';
  END IF;
  IF p_events IS NULL OR jsonb_typeof(p_events) <> 'array'
     OR jsonb_array_length(p_events) > 30 THEN
    RAISE EXCEPTION 'RPG_INVALID_EVENTS';
  END IF;

  SELECT s.id INTO v_student_id
  FROM public.students s
  WHERE s.student_code = btrim(p_student_code)
    AND s.is_active IS NOT FALSE
  LIMIT 1;
  IF v_student_id IS NULL THEN RAISE EXCEPTION 'RPG_STUDENT_NOT_FOUND'; END IF;

  INSERT INTO public.pixel_forest_rpg_profiles (student_id)
  VALUES (v_student_id)
  ON CONFLICT (student_id) DO NOTHING;

  SELECT * INTO v_profile
  FROM public.pixel_forest_rpg_profiles
  WHERE student_id = v_student_id
  FOR UPDATE;

  IF v_profile.last_save_key = p_idempotency_key THEN
    RETURN jsonb_build_object('state_version', v_profile.state_version, 'save_state', v_profile.save_state, 'saved_at', v_profile.updated_at, 'replayed', true);
  END IF;
  IF p_expected_version IS DISTINCT FROM v_profile.state_version THEN
    RAISE EXCEPTION 'RPG_SAVE_CONFLICT:%', v_profile.state_version;
  END IF;

  v_class := NULLIF(p_state->>'hero_class', '');
  v_level := COALESCE((p_state->>'hero_level')::int, 1);
  v_xp := COALESCE((p_state->>'hero_xp')::int, 0);
  v_gold := COALESCE((p_state->>'gold')::int, 0);
  v_gems := COALESCE((p_state->>'gems')::int, 0);
  v_chapter := COALESCE((p_state->>'chapter')::int, 1);
  v_zone := COALESCE(NULLIF(p_state->>'zone', ''), 'village');

  IF v_class NOT IN ('swordsman', 'ranger', 'mage')
     OR v_level NOT BETWEEN 1 AND 50
     OR v_xp NOT BETWEEN 0 AND 10000000
     OR v_gold NOT BETWEEN 0 AND 10000000
     OR v_gems NOT BETWEEN 0 AND 1000000
     OR v_chapter NOT BETWEEN 1 AND 4
     OR v_zone NOT IN ('village', 'mosswood', 'swamp', 'ruins') THEN
    RAISE EXCEPTION 'RPG_STATE_OUT_OF_RANGE';
  END IF;
  IF jsonb_typeof(p_state->'inventory') <> 'object'
     OR jsonb_typeof(p_state->'equipment') <> 'object'
     OR jsonb_typeof(p_state->'unlocked_zones') <> 'array' THEN
    RAISE EXCEPTION 'RPG_STATE_SHAPE_INVALID';
  END IF;

  v_gold_delta := v_gold - v_profile.gold;
  v_gem_delta := v_gems - v_profile.gems;
  IF abs(v_gold_delta) > 10000 OR abs(v_gem_delta) > 1000 THEN
    RAISE EXCEPTION 'RPG_ECONOMY_DELTA_TOO_LARGE';
  END IF;

  v_new_version := v_profile.state_version + 1;
  UPDATE public.pixel_forest_rpg_profiles SET
    hero_class = v_class,
    hero_level = v_level,
    hero_xp = v_xp,
    gold = v_gold,
    gems = v_gems,
    current_chapter = v_chapter,
    current_zone = v_zone,
    save_state = p_state,
    state_version = v_new_version,
    last_save_key = p_idempotency_key,
    last_played_at = now(),
    updated_at = now()
  WHERE student_id = v_student_id;

  IF v_gold_delta <> 0 THEN
    INSERT INTO public.pixel_forest_economy_ledger
      (student_id, currency, amount, balance_after, reason, idempotency_key, metadata)
    VALUES
      (v_student_id, 'gold', v_gold_delta, v_gold, 'save_sync', p_idempotency_key, jsonb_build_object('chapter', v_chapter, 'zone', v_zone))
    ON CONFLICT DO NOTHING;
  END IF;
  IF v_gem_delta <> 0 THEN
    INSERT INTO public.pixel_forest_economy_ledger
      (student_id, currency, amount, balance_after, reason, idempotency_key, metadata)
    VALUES
      (v_student_id, 'gems', v_gem_delta, v_gems, 'save_sync', p_idempotency_key, jsonb_build_object('chapter', v_chapter, 'zone', v_zone))
    ON CONFLICT DO NOTHING;
  END IF;

  FOR v_event IN SELECT value FROM jsonb_array_elements(p_events)
  LOOP
    IF v_event->>'type' IN (
      'session_start', 'session_end', 'class_selected', 'zone_enter', 'monster_kill',
      'player_death', 'boss_start', 'boss_clear', 'chapter_complete', 'item_craft',
      'weapon_enhance', 'rune_equip', 'damage_dealt', 'damage_taken'
    ) THEN
      INSERT INTO public.pixel_forest_balance_events
        (student_id, event_type, hero_class, hero_level, chapter, zone, value, metadata)
      VALUES
        (v_student_id, v_event->>'type', v_class, v_level, v_chapter, v_zone,
         CASE WHEN (v_event->>'value') ~ '^-?[0-9]+([.][0-9]+)?$' THEN (v_event->>'value')::numeric ELSE NULL END,
         COALESCE(v_event->'metadata', '{}'::jsonb));
    END IF;
  END LOOP;

  RETURN jsonb_build_object('state_version', v_new_version, 'save_state', p_state, 'saved_at', now(), 'replayed', false);
END;
$function$;

REVOKE ALL ON FUNCTION public.get_pixel_forest_rpg_state(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.save_pixel_forest_rpg_state(text, int, text, jsonb, jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_pixel_forest_rpg_state(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.save_pixel_forest_rpg_state(text, int, text, jsonb, jsonb) TO anon, authenticated;

/* Replaced below to match the current game_docs schema.
UPDATE public.game_docs SET
  game_format = 'Persistent Canvas 2D top-down pixel-art campaign RPG',
  features = '3 อาชีพ (นักดาบ/นักธนู/นักเวท) · 4 โซน (หมู่บ้าน/ป่ามอส/หนองน้ำ/วิหาร) · แคมเปญ 4 บท · บอส 4 ตัวพร้อมสกิลเฉพาะ · class skills · loot/equipment · Gold/Gem ledger · craft · weapon enhance · rune · persistent save with optimistic version · balance telemetry · KampaiVersus',
  build_version = '3.0.0',
  notes = 'RPG Vertical Slice รุ่น 1: state persistence ผ่าน validated RPC; direct tables admin-only with RLS; balance events whitelist; original pixel art assets',
  updated_at = now()
WHERE item_id = (SELECT id FROM public.educational_hub_items WHERE game_slug = 'pixel-forest-explorer' LIMIT 1);
*/

UPDATE public.educational_hub_items SET
  description = 'RPG พิกเซลอาร์ต 3 อาชีพ ผจญภัย 4 โซน ปราบบอส คราฟอาวุธ ตีบวก และติดตั้งรูน พร้อมระบบเซฟถาวร',
  build_version = '3.0.0',
  build_updated_at = now(),
  updated_at = now()
WHERE game_slug = 'pixel-forest-explorer';

UPDATE public.game_docs SET
  game_format = 'Persistent Canvas 2D top-down pixel-art campaign RPG',
  features = ARRAY[
    '3 อาชีพ: นักดาบ เรนเจอร์ และเมจ พร้อมสกิลเฉพาะอาชีพ',
    'แคมเปญ 4 บท 4 โซน และบอส 4 ตัวที่มีกลไกเฉพาะ',
    'ระบบ loot อุปกรณ์ ทอง อัญมณี คราฟ ตีบวก และรูน',
    'เซฟถาวรแบบ optimistic version และ idempotency',
    'telemetry สำหรับวิเคราะห์บาลานซ์จากการเล่นจริง',
    'KampaiVersus local และ online พร้อม leaderboard'
  ],
  version = '3.0.0',
  notes = 'RPG Vertical Slice รุ่น 1: validated RPC; direct tables admin-only with RLS; balance event whitelist; original pixel art assets',
  updated_at = now()
WHERE item_id = (
  SELECT id FROM public.educational_hub_items
  WHERE game_slug = 'pixel-forest-explorer' LIMIT 1
);
