-- Migration 564: Seed 78 Visual English Questions and Visual Exam Set PIN 6001
-- เพิ่มคลังข้อสอบภาษาอังกฤษ ป.4 เน้นการถาม-ตอบจากรูปภาพสื่อการสอนจริง (Visual English Questions)
-- และสร้างชุดข้อสอบมาตรฐานภาพชุดที่ 2 (PIN: 6001)

INSERT INTO public.exam_questions (
  id,
  subject,
  grade,
  topic,
  difficulty,
  bloom_level,
  question_type,
  question_text,
  options,
  answer,
  explanation,
  indicator_code,
  indicator_desc,
  media_title,
  media_image_url
) VALUES
(
  'e2000000-0000-4000-8000-000000000001',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Jobs & Occupations',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. What does he do?',
  '["He is a doctor.","He is a farmer.","He is a pilot.","He is a singer."]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือคุณหมอ (Doctor) สวมเสื้อกาวน์และหูฟังแพทย์ ประโยคที่ถูกต้องคือ He is a doctor.',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/jobs/doctor.webp'
),
(
  'e2000000-0000-4000-8000-000000000002',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Jobs & Occupations',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. Where does she work?',
  '["In a school","In a hospital","At a police station","On a farm"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือพยาบาล (Nurse) สถานที่ทำงานคือโรงพยาบาล (In a hospital)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/jobs/nurse.webp'
),
(
  'e2000000-0000-4000-8000-000000000003',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Jobs & Occupations',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. What is his job?',
  '["Firefighter","Police officer","Teacher","Dentist"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือเจ้าหน้าที่ตำรวจ (Police officer) สวมเครื่องแบบตำรวจ',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/jobs/police-officer.webp'
),
(
  'e2000000-0000-4000-8000-000000000004',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Jobs & Occupations',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. What does a firefighter do?',
  '["He flies an airplane.","He catches thieves.","He puts out fires.","He cooks meals in a restaurant."]'::jsonb,
  '2'::jsonb,
  'จากรูปภาพคือนักดับเพลิง (Firefighter) มีหน้าที่ดับเพลิง (He puts out fires.)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/jobs/firefighter.webp'
),
(
  'e2000000-0000-4000-8000-000000000005',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Jobs & Occupations',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. What does he do?',
  '["He is a chef.","He is an artist.","He is a driver.","He is a doctor."]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือพ่อครัวหรือเชฟ (Chef) สวมหมวกพ่อครัวสีขาว',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/jobs/chef.webp'
),
(
  'e2000000-0000-4000-8000-000000000006',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Jobs & Occupations',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. What does a pilot fly?',
  '["A bus","A bicycle","A train","An airplane"]'::jsonb,
  '3'::jsonb,
  'จากรูปภาพคือนักบิน (Pilot) มีหน้าที่ขับเครื่องบิน (An airplane)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/jobs/pilot.webp'
),
(
  'e2000000-0000-4000-8000-000000000007',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Jobs & Occupations',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. Where does the farmer work?',
  '["At a supermarket","On a farm","At an airport","In a bank"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือชาวนา/เกษตรกร (Farmer) ทำงานในไร่หรือฟาร์ม (On a farm)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/jobs/farmer.webp'
),
(
  'e2000000-0000-4000-8000-000000000008',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Jobs & Occupations',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. Who takes care of your teeth?',
  '["A dentist","A singer","A driver","A chef"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือทันตแพทย์ (Dentist) เป็นผู้ดูแลรักษาฟัน',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/jobs/dentist.webp'
),
(
  'e2000000-0000-4000-8000-000000000009',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Jobs & Occupations',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. What is her job?',
  '["She is a pilot.","She is a teacher.","She is a farmer.","She is a police officer."]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือคุณครู (Teacher) กำลังสอนหนังสือ',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/jobs/teacher.webp'
),
(
  'e2000000-0000-4000-8000-000000000010',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Jobs & Occupations',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. What does she like doing?',
  '["Cooking soup","Singing songs","Fixing cars","Playing chess"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือนักร้อง (Singer) ถือไมโครโฟนร้องเพลง (Singing songs)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/jobs/singer.webp'
),
(
  'e2000000-0000-4000-8000-000000000011',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Places in Town',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. Where do people go when they are sick?',
  '["To the zoo","To the hospital","To the cinema","To the park"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือโรงพยาบาล (Hospital) มีสัญลักษณ์กากบาทสีแดง',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/places/hospital.webp'
),
(
  'e2000000-0000-4000-8000-000000000012',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Places in Town',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. What can you do in this place?',
  '["Swim in water","Read and borrow books","Buy clothes","Watch a movie"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือห้องสมุด (Library) มีชั้นหนังสือสำหรับอ่านและยืมหนังสือ',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/places/library.webp'
),
(
  'e2000000-0000-4000-8000-000000000013',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Places in Town',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. Where can you see wild animals like lions and giraffes?',
  '["At the zoo","At the post office","At the bank","At the airport"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือสวนสัตว์ (Zoo) ที่มีสัตว์ป่าหลากหลายชนิด',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/places/zoo.webp'
),
(
  'e2000000-0000-4000-8000-000000000014',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Places in Town',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. Where do students study every weekday?',
  '["At a restaurant","At school","At an airport","At a market"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือโรงเรียน (School) สถานที่ที่นักเรียนมาเรียนหนังสือ',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/places/school.webp'
),
(
  'e2000000-0000-4000-8000-000000000015',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Places in Town',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. Where can your mother buy fresh fruits and vegetables?',
  '["At the market","At the library","At the bank","At the post office"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือตลาด (Market) มีแผงขายผักผลไม้สด',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/places/market.webp'
),
(
  'e2000000-0000-4000-8000-000000000016',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Places in Town',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. What place is this?',
  '["A bank","A park","A zoo","A school"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือธนาคาร (Bank) สถานที่สำหรับฝาก-ถอนเงิน',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/places/bank.webp'
),
(
  'e2000000-0000-4000-8000-000000000017',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Places in Town',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. What can children do in the park?',
  '["Fly an airplane","Ride bicycles and play on grass","Buy medicine","Deposit money"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือสวนสาธารณะ (Park) มีต้นไม้ สนามหญ้า สำหรับวิ่งเล่นและปั่นจักรยาน',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/places/park.webp'
),
(
  'e2000000-0000-4000-8000-000000000018',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Places in Town',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. Where do you go to eat dinner with your family?',
  '["A restaurant","A library","A hospital","A post office"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือร้านอาหาร (Restaurant) มีโต๊ะรับประทานอาหารและเมนู',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/places/restaurant.webp'
),
(
  'e2000000-0000-4000-8000-000000000019',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Places in Town',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. Where do you send letters and parcels?',
  '["At the park","At the post office","At the airport","At the zoo"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือที่ทำการไปรษณีย์ (Post office) มีตู้ไปรษณีย์สำหรับส่งจดหมายและพัสดุ',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/places/post-office.webp'
),
(
  'e2000000-0000-4000-8000-000000000020',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Places in Town',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. What place is this?',
  '["An airport","A market","A hospital","A bank"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือสนามบิน (Airport) มีรันเวย์และเครื่องบิน',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/places/airport.webp'
),
(
  'e2000000-0000-4000-8000-000000000021',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Actions & Verbs',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. What is the boy doing?',
  '["He is cooking.","He is sleeping.","He is swimming.","He is singing."]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพเด็กผู้ชายกำลังทำอาหาร (He is cooking.)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/verbs/cook.webp'
),
(
  'e2000000-0000-4000-8000-000000000022',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Actions & Verbs',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. What is the girl doing?',
  '["She is writing.","She is dancing.","She is eating.","She is reading."]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพเด็กผู้หญิงกำลังเต้นรำอย่างสนุกสนาน (She is dancing.)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/verbs/dance.webp'
),
(
  'e2000000-0000-4000-8000-000000000023',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Actions & Verbs',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. What is he doing?',
  '["He is drinking water.","He is cooking soup.","He is jumping high.","He is driving a car."]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพเด็กผู้ชายกำลังดื่มน้ำจากแก้ว (He is drinking water.)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/verbs/drink.webp'
),
(
  'e2000000-0000-4000-8000-000000000024',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Actions & Verbs',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. What is the girl doing?',
  '["She is sleeping.","She is eating food.","She is dancing.","She is singing."]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพเด็กผู้หญิงกำลังรับประทานอาหาร (She is eating food.)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/verbs/eat.webp'
),
(
  'e2000000-0000-4000-8000-000000000025',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Actions & Verbs',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. What action is shown?',
  '["Walking","Jumping","Sitting","Sleeping"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือท่าทางกระโดด (Jumping)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/verbs/jump.webp'
),
(
  'e2000000-0000-4000-8000-000000000026',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Actions & Verbs',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. What is he doing?',
  '["He is singing a song.","He is writing a letter.","He is eating an apple.","He is swimming."]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพเด็กผู้ชายถือไมโครโฟนร้องเพลง (He is singing a song.)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/verbs/sing.webp'
),
(
  'e2000000-0000-4000-8000-000000000027',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Actions & Verbs',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. How does the boy go to school?',
  '["He drives a car.","He walks to school.","He rides a plane.","He swims."]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพเด็กผู้ชายกำลังเดิน (He walks to school.)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/verbs/walk.webp'
),
(
  'e2000000-0000-4000-8000-000000000028',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Actions & Verbs',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. What is the student doing?',
  '["She is writing with a pen.","She is cooking food.","She is jumping.","She is dancing."]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือนักเรียนกำลังเขียนหนังสือลงบนกระดาษ (She is writing with a pen.)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/verbs/write.webp'
),
(
  'e2000000-0000-4000-8000-000000000029',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Actions & Verbs',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. What is the boy doing in bed?',
  '["He is singing.","He is jumping.","He is sleeping.","He is cooking."]'::jsonb,
  '2'::jsonb,
  'จากรูปภาพเด็กผู้ชายนอนหลับอยู่บนเตียง (He is sleeping.)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/verbs/sleep.webp'
),
(
  'e2000000-0000-4000-8000-000000000030',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Actions & Verbs',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. Where is the boy swimming?',
  '["In the sky","In the pool","In the forest","In the classroom"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพเด็กผู้ชายกำลังว่ายน้ำในสระน้ำ (In the pool)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/verbs/swim.webp'
),
(
  'e2000000-0000-4000-8000-000000000031',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Prepositions of Place',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. Where is the object?',
  '["It is under the box.","It is on the box.","It is in the box.","It is behind the box."]'::jsonb,
  '2'::jsonb,
  'จากรูปภาพ วัตถุอยู่ข้างในกล่อง (in the box)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/directions/in.webp'
),
(
  'e2000000-0000-4000-8000-000000000032',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Prepositions of Place',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. Where is the object?',
  '["It is under the box.","It is on the box.","It is in the box.","It is between the boxes."]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพ วัตถุอยู่บนกล่อง (on the box)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/directions/on.webp'
),
(
  'e2000000-0000-4000-8000-000000000033',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Prepositions of Place',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. Where is the object?',
  '["It is on the box.","It is under the box.","It is in the box.","It is in front of the box."]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพ วัตถุอยู่ใต้กล่อง (under the box)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/directions/under.webp'
),
(
  'e2000000-0000-4000-8000-000000000034',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Prepositions of Place',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. Where is the object?',
  '["It is in front of the box.","It is behind the box.","It is on the box.","It is under the box."]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพ วัตถุอยู่ด้านหลังกล่อง (behind the box)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/directions/behind.webp'
),
(
  'e2000000-0000-4000-8000-000000000035',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Prepositions of Place',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. Where is the object?',
  '["It is under the box.","It is between the two boxes.","It is in the box.","It is on the box."]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพ วัตถุอยู่ระหว่างกล่องสองใบ (between the two boxes)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/directions/between.webp'
),
(
  'e2000000-0000-4000-8000-000000000036',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Prepositions of Place',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. Where is the object?',
  '["It is in front of the box.","It is behind the box.","It is under the box.","It is in the box."]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพ วัตถุอยู่ข้างหน้ากล่อง (in front of the box)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/directions/front.webp'
),
(
  'e2000000-0000-4000-8000-000000000037',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Prepositions of Place',
  'easy',
  'L1',
  'mcq',
  'Look at the arrow in the picture. Which way does it point?',
  '["Down","Left","Up","Right"]'::jsonb,
  '2'::jsonb,
  'ลูกศรในภาพชี้ขึ้นข้างบน (Up)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/directions/up.webp'
),
(
  'e2000000-0000-4000-8000-000000000038',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Grammar: Prepositions of Place',
  'medium',
  'L2',
  'mcq',
  'Look at the arrow in the picture. Which way does it point?',
  '["Up","Right","Down","Left"]'::jsonb,
  '2'::jsonb,
  'ลูกศรในภาพชี้ลงข้างล่าง (Down)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/directions/down.webp'
),
(
  'e2000000-0000-4000-8000-000000000039',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Feelings & Emotions',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. How does the girl feel?',
  '["She feels sad.","She feels angry.","She feels happy.","She feels scared."]'::jsonb,
  '2'::jsonb,
  'จากรูปภาพเด็กผู้หญิงยิ้มแย้มสดใส รู้สึกมีความสุข (happy)',
  'ต 1.2 ป.4/5',
  'พูดแสดงความรู้สึกของตนเองเกี่ยวกับเรื่องต่าง ๆ ใกล้ตัว และกิจกรรมต่าง ๆ ตามแบบที่ฟัง',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/emotions/happy.webp'
),
(
  'e2000000-0000-4000-8000-000000000040',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Feelings & Emotions',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. Why is the boy crying?',
  '["Because he is happy.","Because he is sad.","Because he is proud.","Because he is excited."]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพเด็กผู้ชายกำลังร้องไห้ แสดงอารมณ์เศร้า (sad)',
  'ต 1.2 ป.4/5',
  'พูดแสดงความรู้สึกของตนเองเกี่ยวกับเรื่องต่าง ๆ ใกล้ตัว และกิจกรรมต่าง ๆ ตามแบบที่ฟัง',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/emotions/sad.webp'
),
(
  'e2000000-0000-4000-8000-000000000041',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Feelings & Emotions',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. How does he look?',
  '["Tired","Angry","Bored","Happy"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพเด็กผู้ชายคิ้วขมวดและหน้าแดง แสดงอารมณ์โกรธ (angry)',
  'ต 1.2 ป.4/5',
  'พูดแสดงความรู้สึกของตนเองเกี่ยวกับเรื่องต่าง ๆ ใกล้ตัว และกิจกรรมต่าง ๆ ตามแบบที่ฟัง',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/emotions/angry.webp'
),
(
  'e2000000-0000-4000-8000-000000000042',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Feelings & Emotions',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. The boy sees a spider. He feels _____.',
  '["scared","happy","bored","proud"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพเด็กผู้ชายแสดงอาการตกใจหวาดกลัว (scared)',
  'ต 1.2 ป.4/5',
  'พูดแสดงความรู้สึกของตนเองเกี่ยวกับเรื่องต่าง ๆ ใกล้ตัว และกิจกรรมต่าง ๆ ตามแบบที่ฟัง',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/emotions/scared.webp'
),
(
  'e2000000-0000-4000-8000-000000000043',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Feelings & Emotions',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. After running 10 kilometers, he feels _____.',
  '["excited","tired","angry","proud"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพแสดงอาการหมดแรง เหนื่อยล้า (tired)',
  'ต 1.2 ป.4/5',
  'พูดแสดงความรู้สึกของตนเองเกี่ยวกับเรื่องต่าง ๆ ใกล้ตัว และกิจกรรมต่าง ๆ ตามแบบที่ฟัง',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/emotions/tired.webp'
),
(
  'e2000000-0000-4000-8000-000000000044',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Feelings & Emotions',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. When she opens the surprise gift, she feels _____.',
  '["bored","angry","surprised","sad"]'::jsonb,
  '2'::jsonb,
  'จากรูปภาพตาโตและอ้าปากค้าง แสดงอาการประหลาดใจ (surprised)',
  'ต 1.2 ป.4/5',
  'พูดแสดงความรู้สึกของตนเองเกี่ยวกับเรื่องต่าง ๆ ใกล้ตัว และกิจกรรมต่าง ๆ ตามแบบที่ฟัง',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/emotions/surprised.webp'
),
(
  'e2000000-0000-4000-8000-000000000045',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Feelings & Emotions',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. He has nothing to do. He feels _____.',
  '["happy","excited","bored","scared"]'::jsonb,
  '2'::jsonb,
  'จากรูปภาพแสดงท่าทางเบื่อหน่าย ไม่มีอะไรทำ (bored)',
  'ต 1.2 ป.4/5',
  'พูดแสดงความรู้สึกของตนเองเกี่ยวกับเรื่องต่าง ๆ ใกล้ตัว และกิจกรรมต่าง ๆ ตามแบบที่ฟัง',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/emotions/bored.webp'
),
(
  'e2000000-0000-4000-8000-000000000046',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Feelings & Emotions',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. He won first place in the race. He feels _____.',
  '["proud","sad","scared","tired"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพแสดงความภาคภูมิใจในความสำเร็จ (proud)',
  'ต 1.2 ป.4/5',
  'พูดแสดงความรู้สึกของตนเองเกี่ยวกับเรื่องต่าง ๆ ใกล้ตัว และกิจกรรมต่าง ๆ ตามแบบที่ฟัง',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/emotions/proud.webp'
),
(
  'e2000000-0000-4000-8000-000000000047',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sea Animals',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. What sea animal can jump high and is very friendly?',
  '["A shark","A dolphin","A crab","A jellyfish"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือโลมา (Dolphin) สัตว์เลี้ยงลูกด้วยนมในทะเลที่ฉลาดและเป็นมิตร',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sea-animals/dolphin.webp'
),
(
  'e2000000-0000-4000-8000-000000000048',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sea Animals',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. How many arms does an octopus have?',
  '["Two arms","Four arms","Six arms","Eight arms"]'::jsonb,
  '3'::jsonb,
  'จากรูปภาพคือหมึกยักษ์ (Octopus) มีหนวดทั้งหมด 8 เส้น (Eight arms)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sea-animals/octopus.webp'
),
(
  'e2000000-0000-4000-8000-000000000049',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sea Animals',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. What dangerous fish has sharp teeth and a dorsal fin?',
  '["A shark","A goldfish","A turtle","A shrimp"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือปลาฉลาม (Shark) นักล่าแห่งท้องทะเล',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sea-animals/shark.webp'
),
(
  'e2000000-0000-4000-8000-000000000050',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sea Animals',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. What animal carries a hard shell and swims in the sea?',
  '["A sea turtle","A whale","A dolphin","An octopus"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือเต่าทะเล (Sea turtle) มีกระดองแข็งปกป้องลำตัว',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sea-animals/turtle.webp'
),
(
  'e2000000-0000-4000-8000-000000000051',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sea Animals',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. What animal walks sideways and has two big claws?',
  '["A crab","A jellyfish","A whale","A shark"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือปู (Crab) เดินไปด้านข้างและมีก้ามขนาดใหญ่ 2 ก้าม',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sea-animals/crab.webp'
),
(
  'e2000000-0000-4000-8000-000000000052',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sea Animals',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. What soft and transparent sea animal is this?',
  '["A dolphin","A jellyfish","A sea turtle","A crab"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือแมงกะพรุน (Jellyfish) ลำตัวใสและนิ่ม',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sea-animals/jellyfish.webp'
),
(
  'e2000000-0000-4000-8000-000000000053',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sea Animals',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. What is the largest animal in the ocean?',
  '["A whale","A crab","A shrimp","A clownfish"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือวาฬ (Whale) สัตว์ที่มีขนาดใหญ่ที่สุดในมหาสมุทร',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sea-animals/whale.webp'
),
(
  'e2000000-0000-4000-8000-000000000054',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sea Animals',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. What small sea animal with long antennae is this?',
  '["A shrimp","A whale","A shark","A dolphin"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือกุ้ง (Shrimp) มีหนวดยาวและตัวงอ',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sea-animals/shrimp.webp'
),
(
  'e2000000-0000-4000-8000-000000000055',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sports & Activities',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. What sport do players kick the ball into a net?',
  '["Basketball","Football","Tennis","Badminton"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือกีฬาฟุตบอล (Football) ใช้เท้าเตะลูกบอลเข้าประตู',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sports/football.webp'
),
(
  'e2000000-0000-4000-8000-000000000056',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sports & Activities',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. What sport do players bounce and shoot the ball into a hoop?',
  '["Basketball","Volleyball","Boxing","Running"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือกีฬาบาสเกตบอล (Basketball) โยนลูกบอลลงห่วง',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sports/basketball.webp'
),
(
  'e2000000-0000-4000-8000-000000000057',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sports & Activities',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. What do you need to play badminton?',
  '["A racket and a shuttlecock","A football and gloves","A basketball and a hoop","A swimming cap"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือกีฬาแบดมินตัน (Badminton) ใช้อุปกรณ์คือไม้แร็กเก็ตและลูกขนไก่ (shuttlecock)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sports/badminton.webp'
),
(
  'e2000000-0000-4000-8000-000000000058',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sports & Activities',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. What sport is played on a court with a green-yellow ball?',
  '["Tennis","Boxing","Football","Volleyball"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือกีฬาเทนนิส (Tennis)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sports/tennis.webp'
),
(
  'e2000000-0000-4000-8000-000000000059',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sports & Activities',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. What sport is done in water?',
  '["Running","Swimming","Basketball","Boxing"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือกีฬาว่ายน้ำ (Swimming)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sports/swimming.webp'
),
(
  'e2000000-0000-4000-8000-000000000060',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sports & Activities',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. What athletic activity is this?',
  '["Running","Cooking","Sleeping","Reading"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือกิจกรรมการวิ่ง (Running)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sports/running.webp'
),
(
  'e2000000-0000-4000-8000-000000000061',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sports & Activities',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. In which sport do players hit the ball over a net using their hands?',
  '["Volleyball","Football","Swimming","Running"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือกีฬาวอลเลย์บอล (Volleyball) ตบลูกบอลข้ามตาข่ายด้วยมือ',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sports/volleyball.webp'
),
(
  'e2000000-0000-4000-8000-000000000062',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Sports & Activities',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. What combat sport requires wearing padded gloves?',
  '["Boxing","Tennis","Badminton","Basketball"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือกีฬามวย (Boxing) สวมนวมชกมวย',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/sports/boxing.webp'
),
(
  'e2000000-0000-4000-8000-000000000063',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Rooms in the House',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. Which room is used for cooking and preparing meals?',
  '["The bedroom","The kitchen","The bathroom","The garage"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือห้องครัว (Kitchen) มีเตาและอุปกรณ์ทำอาหาร',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/house-rooms/kitchen.webp'
),
(
  'e2000000-0000-4000-8000-000000000064',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Rooms in the House',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. Which room has a bed where you sleep at night?',
  '["The bedroom","The dining room","The kitchen","The garage"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือห้องนอน (Bedroom) มีเตียงนอน',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/house-rooms/bedroom.webp'
),
(
  'e2000000-0000-4000-8000-000000000065',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Rooms in the House',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. Where do you take a shower and brush your teeth?',
  '["In the kitchen","In the bathroom","In the bedroom","In the garage"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือห้องน้ำ (Bathroom) มีฝักบัวและอ่างล้างหน้า',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/house-rooms/bathroom.webp'
),
(
  'e2000000-0000-4000-8000-000000000066',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Rooms in the House',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. Where does the family sit together on sofas to watch TV?',
  '["In the living room","In the bathroom","In the garage","In the kitchen"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือห้องนั่งเล่น (Living room) มีโซฟาและโทรทัศน์',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/house-rooms/living-room.webp'
),
(
  'e2000000-0000-4000-8000-000000000067',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Rooms in the House',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. Where do family members sit around a big table to eat dinner?',
  '["In the dining room","In the bathroom","In the bedroom","In the garage"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือห้องรับประทานอาหาร (Dining room) มีโต๊ะอาหารและเก้าอี้',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/house-rooms/dining-room.webp'
),
(
  'e2000000-0000-4000-8000-000000000068',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Rooms in the House',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. Where do people park their cars at home?',
  '["In the kitchen","In the garage","In the bathroom","In the bedroom"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพคือโรงจอดรถ (Garage)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/house-rooms/garage.webp'
),
(
  'e2000000-0000-4000-8000-000000000069',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Weather & Seasons',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. There are many gray clouds in the sky. The weather is _____.',
  '["sunny","cloudy","snowy","hot"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพท้องฟ้ามีเมฆมาก (cloudy)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/weather/cloudy.webp'
),
(
  'e2000000-0000-4000-8000-000000000070',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Weather & Seasons',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. Rain is falling from the sky. It is _____.',
  '["rainy","sunny","hot","dry"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพมีฝนตก (rainy) ต้องพกร่ม',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/weather/rainy.webp'
),
(
  'e2000000-0000-4000-8000-000000000071',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Weather & Seasons',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. The bright sun is shining. It is _____.',
  '["sunny and hot","snowy and cold","rainy and wet","stormy"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพพระอาทิตย์ส่องแสงเจิดจ้า อากาศแดดจัดและอบอุ่น (sunny and hot)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/weather/sunny.webp'
),
(
  'e2000000-0000-4000-8000-000000000072',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Weather & Seasons',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. The wind blows hard and trees are bending. It is _____.',
  '["windy","sunny","hot","calm"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพลมพัดแรงจนต้นไม้เอนเอียง (windy)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/weather/windy.webp'
),
(
  'e2000000-0000-4000-8000-000000000073',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Weather & Seasons',
  'easy',
  'L1',
  'mcq',
  'Look at the picture. White snowflakes are falling everywhere. It is _____.',
  '["hot and dry","snowy and cold","sunny","rainy"]'::jsonb,
  '1'::jsonb,
  'จากรูปภาพมีหิมะตกขาวโพลน อากาศหนาวเย็นมาก (snowy and cold)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/weather/snowy.webp'
),
(
  'e2000000-0000-4000-8000-000000000074',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Weather & Seasons',
  'medium',
  'L2',
  'mcq',
  'Look at the picture. Dark clouds, thunder, and lightning are shown. The weather is _____.',
  '["stormy","sunny","clear","warm"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพมีฟ้าร้อง ฟ้าผ่า และเมฆดำมืด เป็นพายุฝนฟ้าคะนอง (stormy)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/weather/stormy.webp'
),
(
  'e2000000-0000-4000-8000-000000000075',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Toys & Objects',
  'hard',
  'L1',
  'mcq',
  'Look at the picture. What mechanical toy has metal buttons and lights?',
  '["A robot","A doll","A balloon","A kite"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือของเล่นหุ่นยนต์ (Robot)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/toys/robot.webp'
),
(
  'e2000000-0000-4000-8000-000000000076',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Toys & Objects',
  'easy',
  'L2',
  'mcq',
  'Look at the picture. What colorful toy flies high in the wind attached to a string?',
  '["A kite","A car","A teddy bear","A puzzle"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือว่าว (Kite) ที่ลอยอยู่บนฟ้าด้วยแรงลม',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/toys/kite.webp'
),
(
  'e2000000-0000-4000-8000-000000000077',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Toys & Objects',
  'medium',
  'L1',
  'mcq',
  'Look at the picture. What soft stuffed animal do children love to hug?',
  '["A teddy bear","A robot","A kite","Blocks"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือตุ๊กตาหมีขนนุ่ม (Teddy bear)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/toys/teddy-bear.webp'
),
(
  'e2000000-0000-4000-8000-000000000078',
  'ภาษาอังกฤษ',
  'ป.4',
  'Visual Vocabulary: Toys & Objects',
  'hard',
  'L2',
  'mcq',
  'Look at the picture. What light, colorful object floats in the air when filled with gas?',
  '["A balloon","A book","A pencil","A chair"]'::jsonb,
  '0'::jsonb,
  'จากรูปภาพคือลูกโป่งสวรรค์ (Balloon)',
  'ต 1.1 ป.4/3',
  'เลือก/ระบุภาพ หรือสัญลักษณ์ หรือเครื่องหมาย ตรงตามความหมายของประโยคและข้อความสั้น ๆ ที่ฟัง หรืออ่าน',
  'คลังภาพคำศัพท์ภาษาอังกฤษ ป.4 (Visual English Hub)',
  '/games/english/vocab-hub-assets/toys/balloon.webp'
)
ON CONFLICT (id) DO UPDATE SET
  question_text = EXCLUDED.question_text,
  options = EXCLUDED.options,
  answer = EXCLUDED.answer,
  explanation = EXCLUDED.explanation,
  topic = EXCLUDED.topic,
  indicator_code = EXCLUDED.indicator_code,
  indicator_desc = EXCLUDED.indicator_desc,
  media_title = EXCLUDED.media_title,
  media_image_url = EXCLUDED.media_image_url;

-- สร้างชุดข้อสอบมาตรฐานภาษาอังกฤษภาพชุดที่ 2 (PIN: 6001) รวม 20 ข้อ
INSERT INTO public.exam_sets (
  id,
  title,
  subject,
  grade,
  time_limit_minutes,
  pass_threshold_pct,
  pin_code,
  is_active,
  questions
)
SELECT
  '60010000-0000-4000-8000-000000000001'::uuid,
  'แบบทดสอบภาษาอังกฤษภาพคำศัพท์และชีวิตประจำวัน ป.4 (20 ข้อ)',
  'ภาษาอังกฤษ',
  'ป.4',
  30,
  50,
  '6001',
  true,
  COALESCE(
    (
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', q.id,
          'question_text', q.question_text,
          'options', q.options,
          'answer', q.answer,
          'question_type', q.question_type,
          'difficulty', q.difficulty,
          'bloom_level', q.bloom_level,
          'indicator_code', q.indicator_code,
          'indicator_desc', q.indicator_desc,
          'media_title', q.media_title,
          'media_image_url', q.media_image_url,
          'explanation', q.explanation
        )
      )
      FROM (
        SELECT *
        FROM public.exam_questions
        WHERE id IN (
          'e2000000-0000-4000-8000-000000000001',
          'e2000000-0000-4000-8000-000000000003',
          'e2000000-0000-4000-8000-000000000004',
          'e2000000-0000-4000-8000-000000000005',
          'e2000000-0000-4000-8000-000000000011',
          'e2000000-0000-4000-8000-000000000012',
          'e2000000-0000-4000-8000-000000000013',
          'e2000000-0000-4000-8000-000000000021',
          'e2000000-0000-4000-8000-000000000022',
          'e2000000-0000-4000-8000-000000000023',
          'e2000000-0000-4000-8000-000000000031',
          'e2000000-0000-4000-8000-000000000032',
          'e2000000-0000-4000-8000-000000000033',
          'e2000000-0000-4000-8000-000000000039',
          'e2000000-0000-4000-8000-000000000040',
          'e2000000-0000-4000-8000-000000000047',
          'e2000000-0000-4000-8000-000000000055',
          'e2000000-0000-4000-8000-000000000063',
          'e2000000-0000-4000-8000-000000000070',
          'e2000000-0000-4000-8000-000000000075'
        )
      ) q
    ),
    '[]'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  subject = EXCLUDED.subject,
  grade = EXCLUDED.grade,
  time_limit_minutes = EXCLUDED.time_limit_minutes,
  pass_threshold_pct = EXCLUDED.pass_threshold_pct,
  pin_code = EXCLUDED.pin_code,
  is_active = EXCLUDED.is_active,
  questions = EXCLUDED.questions;
