// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // เกมออนไลน์ (kampai-net/kampai-match) ส่ง broadcast 15-20Hz — ค่า default ของ supabase-js
  // คือ eventsPerSecond: 10 ซึ่ง throttle เกมแอ็กชันให้กระตุก. ยกเป็น 30 เพื่อรองรับ network tick
  // (server tenant limit ~100/s → ปลอดภัย). ดู kampai-net.js / PlayGame.tsx realtime relay
  realtime: {
    params: { eventsPerSecond: 30 },
  },
});